axf-master/AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('App.urls',namespace='axf'))
]

axf-master/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^market/(\d+)/$', views.market, name='market'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^registe/$',views.registe, name='registe')
]

axf-master/App/models.py
from django.db import models

# Create your models here.
class Base(models.Model):
    img = models.CharField(max_length=100)

    name = models.CharField(max_length=100)

    trackid = models.CharField(max_length=10)


    class Meta:
        abstract = True

class Wheel(Base):
    class Meta:
        db_table = 'axf_wheel'

class Nav(Base):
    class Meta:
        db_table = 'axf_nav'

class Mustbuy(Base):
    class Meta:
        db_table = 'axf_mustbuy'

class Shop(Base):
    class Meta:
        db_table = 'axf_shop'

        # (trackid, name, img, categoryid, brandname, img1, childcid1, productid1, longname1, price1,
        #              marketprice1, img2, childcid2, productid2, longname2, price2, marketprice2, img3, childcid3,
        #              productid3, longname3, price3, marketprice3)


class MainShow(models.Model):
    trackid = models.CharField(max_length=8)
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=8)
    brandname = models.CharField(max_length=50)

    img1 = models.CharField(max_length=100)
    childcid1 = models.CharField(max_length=8)
    productid1 = models.CharField(max_length=8)
    longname1 = models.CharField(max_length=100)
    price1 = models.FloatField()
    marketprice1 = models.FloatField()


    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=8)
    productid2 = models.CharField(max_length=8)
    longname2 = models.CharField(max_length=100)
    price2 = models.FloatField()
    marketprice2 = models.FloatField()


    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=8)
    productid3 = models.CharField(max_length=8)
    longname3 = models.CharField(max_length=100)
    price3 = models.FloatField()
    marketprice3 = models.FloatField()



class Foodtypes(models.Model):
    typeid = models.CharField(max_length=8)
    typename = models.CharField(max_length=100)
    childtypenames = models.CharField(max_length=256)
    typesort = models.IntegerField()
    class Meta:
        db_table = 'axf_foodtypes'



# (,,,,,,,,,,,,,,)

class Goods(models.Model):
    productid=models.CharField(max_length=10)
    productimg=models.CharField(max_length=100)
    productname=models.CharField(max_length=100)
    productlongname=models.CharField(max_length=100)
    isxf=models.BooleanField(default=False)
    pmdesc=models.BooleanField(default=False)
    specifics=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=7,decimal_places=2)
    marketprice=models.DecimalField(max_digits=7,decimal_places=2)

    categoryid=models.IntegerField()
    childcid=models.IntegerField()
    childcidname=models.CharField(max_length=100)
    dealerid=models.CharField(max_length=10)
    storenums=models.IntegerField()
    productnum=models.IntegerField()


    class Meta:
        db_table = 'axf_goods'


class User(models.Model):
    account = models.CharField(max_length=80,unique=True)

    password = models.CharField(max_length=256)

    name = models.CharField(max_length=100)

    phone = models.CharField(max_length=20,unique=True)

    addr = models.CharField(max_length=256)

    img = models.CharField(max_length=100)
    rank = models.IntegerField(default=1)

    token = models.CharField(max_length=256)

    class Meta:
        db_table = 'axf_user'

axf-master/App/views.py
from django.shortcuts import render

# Create your views here.


from App.models import Nav, Mustbuy, Wheel, Shop, MainShow, Foodtypes, Goods


def home(request):

    navs = Nav.objects.all()



    mustbuys = Mustbuy.objects.all()



    wheels = Wheel.objects.all()

    shop = Shop.objects.all()
    shophead = shop[0]
    shoptab = shop[1:3]
    shopclass = shop[3:7]
    shopcommend = shop[7:11]



    mainshows = MainShow.objects.all()




    data = {
        'wheels':wheels,
        'navs':navs,
        'mustbuys':mustbuys,
        'shophead':shophead,
        'shoptab':shoptab,
        'shopclass':shopclass,
        'shopcommend':shopcommend,
        'mainshows':mainshows
    }

    return render(request,'home/home.html',context= data)


def market(request,categoryid):

    foodtypes = Foodtypes.objects.all()
    # goodsList = Goods.objects.all()[0:5]
    goodsList = Goods.objects.filter(categoryid=categoryid)
    data = {
        'foodtypes':foodtypes,
        'goodsList':goodsList
    }

    return render(request,'market/market.html',context=data)


def mine(request):
    return render(request,'mine/mine.html')


def cart(request):
    return render(request,'cart/cart.html')


def registe(request):
    if request.method == 'GET':
        pass
    elif request.method == 'POST':
        pass
    return render(request,'mine/registe.html')

axf-master/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
{#  CSS#}
    {% block extcss %}
    {% endblock %}

    <title>
{#      标题#}
        {% block title %}
        {% endblock %}
    </title>
</head>


<body>
{# 头部#}
{% block header %}
    <header>爱鲜蜂</header>
{% endblock %}

{# 主体内容#}
<div class="hidescroll">
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
</div>



{# 尾部#}
{% block footer %}
    <footer><a href="{% url 'axf:home' %}" class = 'home'>
        <dl>
            <dt><span></span></dt>
            <dd> 首页 </dd>
        </dl>
    </a>
    <a href="{% url 'axf:market' 104749 %}" class ='market'>
        <dl>
            <dt><span></span></dt>
            <dd> 散购超市 </dd>
        </dl>
    </a>
    <a href="{% url 'axf:cart' %}" class = 'cart'>
        <dl>
            <dt><span></span></dt>
            <dd> 购物车 </dd>
        </dl>
    </a>
    <a href="{% url 'axf:mine' %}" class = 'mine'>
        <dl>
            <dt><span></span></dt>
            <dd> 我的 </dd>
        </dl>
    </a>
    </footer>
{% endblock %}

</body>


<script src="{% static 'base/js/jquery.js' %}"></script>
<script src="{% static 'base/js/bootstrap.js' %}"></script>
<script src="{% static 'base/js/swiper.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{# JS#}
{% block extjs %}
{% endblock %}

</html>

axf-master/templates/cart/cart.html
{% extends 'base/base.html' %}

{% block title %}
    爱鲜蜂 | 购物车
{% endblock %}

{% block content %}
    购物车
{% endblock %}

axf-master/templates/home/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

{% block title %}
    爱鲜蜂 | 首页
{% endblock %}

{% block content %}
    <div class="home">
        <div class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                {% for wheel in wheels %}
                    <div class="swiper-slide">
                        <img src="{{ wheel.img }}" alt="">
                    </div>
                {% endfor %}
            </div>

            <div class="swiper-pagination"></div>
        </div>


        <div class="nav">
            <ul>
                {% for nav in navs %}
                    <li>
                        <img src="{{ nav.img }}" alt="">
                        <span> {{ nav.name }}</span>
                    </li>
                {% endfor %}
            </ul>
        </div>


        <div class="swiper-container" id="mustbuySwiper">
            <div class="swiper-wrapper">
                {% for mustbuy in mustbuys %}
                    <div class="swiper-slide">
                        <img src="{{ mustbuy.img }}" alt="">
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="shop">
    <div class="shophead">
        <a href="#">
            <img src="{{ shophead.img }}" alt="">
        </a>
    </div>
    <div class="shoptab">
        {% for tab in shoptab %}
            <a href="#">
                <img src="{{ tab.img }}" alt="">
            </a>
        {% endfor %}
        
    </div>
    <ul class="shopclass">
        {% for item in shopclass %}
            <li>
            <a href="#">
                <img src="{{ item.img }}" alt="">
            </a>
            </li>
        {% endfor %}
        
    </ul>
    <ul class="shopcommend">
        {% for com in shopcommend %}
        <li>
            <a href="#">
                <img src="{{ com.img }}" alt="">
            </a>
        </li>
        {% endfor %}
        
    </ul>

 <div class="main">
     {% for mainshow in mainshows %}
        <div class="main-wrapper">


        <div class='title'>
            {{ mainshow.name }}
            <a href="#">更多</a>
            <span></span>
        </div>



            <div class="headimg">

                <img src="{{ mainshow.img }}" alt="">

            </div>

            <div class="shoplist">
                <div class="shopitem">
                    <a href="#">
                        <img src="{{ mainshow.img1 }}" alt="" class="img">
                        <span class="desc">
                            {{ mainshow.longname1 }}
                        </span>
                        <span class="price">
                            {{ mainshow.price1 }}
                        </span>
                        <span class="marketprice">
                            {{ mainshow.marketprice1 }}
                        </span>
                    </a>
                    <button><span>+</span></button>
                </div>

                <div class="shopitem">
                    <a href="#">
                        <img src="{{ mainshow.img2 }}" alt="" class="img">
                        <span class="desc">
                            {{ mainshow.longname2 }}
                        </span>
                        <span class="price">
                            {{ mainshow.price2 }}
                        </span>
                        <span class="marketprice">
                            {{ mainshow.marketprice2}}
                        </span>
                    </a>
                    <button><span>+</span></button>
                </div>

                <div class="shopitem">
                    <a href="#">
                        <img src="{{ mainshow.img3 }}" alt="" class="img">
                        <span class="desc">
                            {{ mainshow.longname3 }}
                        </span>
                        <span class="price">
                            {{ mainshow.price3 }}
                        </span>
                        <span class="marketprice">
                            {{ mainshow.marketprice3 }}
                        </span>
                    </a>

                    <button><span>+</span></button>

                </div>
            </div>
        </div>
     {% endfor %}

    </div>
    </div>
{% endblock %}

axf-master/templates/market/market.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}
{% block title %}
    爱鲜蜂 | 闪购超市
{% endblock %}

{% block content %}
    <div class="market">
    <div class="type-slider">
    <ul>
        {% for foodtype in foodtypes %}
                <li class="type-item">
                <span></span>
                    <a href="{% url 'axf:market' foodtype.typeid %}">
                        {{ foodtype.typename }}
                    </a>
                </li>
        {% endfor %}

    </ul>
</div>
    <nav>
        <ul>
            <li>
                <span>
                    全部类型
                    <i class="glyphicon glyphicon-triangle-top"></i>
                </span>
            </li>
            <li>
                <span>
                    综合排序
                    <i class="glyphicon glyphicon-triangle-top"></i>
                </span>
            </li>
        </ul>
    </nav>


    <div class="main-content">
    <div class="content-wrapper">
        <ul>
             {% for goods in goodsList %}
                 <li>
                 <a href="#">
                     <img src="{{ goods.productimg }}" alt=""
                     class="goods-img">
                 <div class="goods-info">


                 <p class="name">{{ goods.productlongname }}</p>
                     <p class="detailtag">
                         {% if goods.isxf %}
                            <span class="'xf">精选</span>
                         {% endif %}
                     </p>
                 <p class="specifics">{{ goods.specifics }}</p>

                 <p class="price">
                     <span class="now-price">{{ goods.price }}</span>
                     <span class="market-price">{{ goods.marketprice }}</span>
                 </p>
                 </div>
                 </a>


                 <div class="bt-wrapper">
                     <span class="glyphicon glyphicon-minus"></span>
                     <span class="num">10</span>
                     <span class="glyphicon glyphicon-plus"></span>
                 </div>
                 </li>
             {% endfor %}

        </ul>
    </div>
    </div>
    </div>
{% endblock %}

axf-master/templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}
{% block title %}
    爱鲜蜂 | 我的
{% endblock %}

{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="{% static 'uploads/qq.jpg' %}" alt="">
            </div>
            <div class="user-content">
                <p>
                    <a href="#">
                        <span class="glyphicon glyphicon-user"></span>
                        未登陆
                    </a>
                </p>
                <p>
                    <span class="glyphicon glyphicon-certificate"></span>
                    暂无等级
                </p>
                <a href="{% url 'axf:registe' %}" class="register">注册</a>
            </div>
        </div>

        <div class="collect">
            <span class="glyphicon glyphicon-pushpin"></span>
            <i>收藏</i>
        </div>

        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="#">查看订单 <b class="glyphicon glyphicon-chevron-right"></b> </a>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><b class="glyphicon glyphicon-shopping-cart">

                                </b></dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <dl>
                                <dt><b class="glyphicon glyphicon-earphone">

                                </b></dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <dl>
                                <dt><b class="glyphicon glyphicon-glass">

                                </b></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <dl>
                                <dt><b class="glyphicon glyphicon-dashboard">

                                </b></dt>
                                <dd>待退款</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><b class="glyphicon glyphicon-hdd">

                                </b></dt>
                                <dd>优惠卷</dd>
                            </dl>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <dl>
                                <dt><b class="glyphicon glyphicon-qrcode">

                                </b></dt>
                                <dd>收获地址</dd>
                            </dl>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <dl>
                                <dt><b class="glyphicon glyphicon-gbp">

                                </b></dt>
                                <dd>客户反馈</dd>
                            </dl>
                        </a>
                    </li>

                    <li>
                        <a href="#">
                            <dl>
                                <dt><b class="glyphicon glyphicon-saved">

                                </b></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            <section class="quit">
                <a href="#">退出</a>
            </section>
        </div>
    </div>
{% endblock %}

axf-master/templates/mine/registe.html
{% extends 'base/base.html' %}
{% load static %}
{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/registe.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/registeAXF.js' %}"></script>
{% endblock %}

{% block title %}
    爱鲜蜂 | 注册
{% endblock %}

{% block content %}
    <div class="register">
    <div class="back">
        <a href="{% url 'axf:mine' %}">
            <span class="glyphicon glyphicon-remove"></span>
        </a>
    </div>
        <form action="{% url 'axf:registe' %}" method="post">



            <div class="form-group  has-feedback" id = 'account'>
                <div class="input-group">
                    <div class="input-group-addon">账号</div>

                    <input type="text" class="form-control" placeholder="数字,字母" name="account">
                    <span class="glyphicon  form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>





            <div class="form-group" id="password">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="6-12位密码" name="password">
                 <span class="glyphicon  form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>



            <div class="form-group" id="passwd">
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" placeholder="确认密码" name="passwd">
                 <span class="glyphicon  form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
                </div>

                <div class="form-group" id="phone">
                <div class="input-group">
                    <div class="input-group-addon">手机</div>
                    <input type="text" class="form-control" placeholder="11位" name="phone">
                 <span class="glyphicon  form-control-feedback" aria-hidden="true"></span>
                </div>
                <i></i>
            </div>

                <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">地址</div>
                    <input type="text" class="form-control" placeholder="收货地址（默认选项）" name="addr">
                </div>
            </div>


                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">头像</div>
                        <input type="file" name="icon">
                    </div>
                </div>


            <input type="submit" id="subButton" value="注册">
        </form>
    </div>
{% endblock %}