jlg01_01/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^cart/(\d+)/$',views.cart,name='cart'),
    url(r'^list/$',views.list,name='list'),
    url(r'^load/$',views.load,name='load'),
    url(r'^product/(\d+)/$',views.product,name='product'),
    url(r'^register',views.register,name='register')
]

jlg01_01/jlg/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('App.urls',namespace='jlg'))
]

jlg01_01/App/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.BigIntegerField(unique=True)
    password = models.CharField(max_length=256)


class Wheel(models.Model):
    img = models.CharField(max_length=100)
    class Meta:
        db_table='App_wheel'


class Goods(models.Model):
    img = models.CharField(max_length=100)
    prse = models.IntegerField()
    goodsname = models.CharField(max_length=100)


class Cart(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(Goods)
    number = models.IntegerField()
    isselect = models.BooleanField(default=True)

jlg01_01/App/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from App.models import Wheel, User, Goods


def index(request):
    wheels = Wheel.objects.all()
    goods = Goods.objects.all()
    return render(request, 'index.html', context={'wheel': wheels,'goods':goods})



def cart(request,id):
    goods = Goods.objects.filter(id=id).first()
    return render(request,'cart.html',context={'goods':goods})


def list(request):
    return render(request,'list.html')







def load(request):
    if request.method == 'GET':
        return render(request,'load.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username,password)

        users = User.objects.filter(username=username).filter(password=password)
        if users.count():
            user = users.first()
            response = redirect('jlg:index')
            response.set_cookie('username',user.username)
            return response
        else:
            return HttpResponse('用户名或者密码错误！')


def product(request,id):
    goods = Goods.objects.filter(id=id).first()

    return render(request,'product.html',context={'goods':goods})


def register(request):
    if request.method == 'GET':
        return render(request,'register.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username,password)
        user = User()
        user.username = username
        user.password = password
        user.save()

        response = redirect('jlg:index')
        response.set_cookie('username',username)
    return response

jlg01_01/templates/cart.html
{% load static %}
<!DOCT
YPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>我的购物车-嘉丽购</title>
    <link rel="stylesheet" type="text/css" href='{% static "css/cart.css" %}'/>
    <link rel="stylesheet" type="text/css" href='{% static "css/footer.css" %}'/>
    <script src='{% static "js/jquery-1.12.0.js" %}' type="text/javascript" charset="utf-8"></script>
    <script src='{% static "js/jquery-1.12.0.js" %}' type="text/javascript" charset="utf-8"></script>
    <script src='{% static "js/jquery-1.12.0.js" %}' type="text/javascript" charset="utf-8"></script>
    <script src='{% static "js/cart.js" %}' type="text/javascript" charset="utf-8"></script>


</head>
<body>

<div class="bigbox">
    <!--header部分-->
    <div id="header">
        <div class="phone fl">
            <img src="{% static 'img/header/phone1.jpg' %}">
            <h6>电话热线</h6>
            <h5>400-630-0077</h5>
        </div>
        <div class="login fl">
            <a href="#" class="loads">[登录]</a>
            <a href="#" class="register">[免费注册]</a>
        </div>
        <div class="car fr">
            <p>
                <a href="#">我的嘉</a>
                <a href="#">我的订单</a>
                <a href="#">客户服务</a>
                <a href="#">电视会员激活</a>
                <a href="#">手机嘉丽购</a>
            </p>
        </div>
    </div>
    <!--nav部分-->
    <div id="nav">
        <div class="logo fl">
            <img src="{% static 'img/nav/nav1.jpg' %}">
        </div>
        <div class="cart">购物车</div>
        <div class="all">全部商品</div>
        <div class="return"><a href="index.html">返回首页</a></div>
        <div class="waitFor">
            <img src="{% static 'img/nav/cart.jpg' %}">
        </div>
    </div>
    <div id="content">
        <div class="content">
            <div class="c_head">
                <p>
                    <span class="span_1">全选</span>
                    <span class="span_2">商品名</span>
                    <span class="span_3">单价（元）</span>
                    <span class="span_4">数量</span>
                    <span class="span_5">嘉丽价</span>
                    <span class="span_6">操作</span>

                </p>
            </div>

            <div class="main first-main" style="display: block;">
                <div class="cart_div fl"><input type="checkbox" checked="checked" class="_true"></div>
                <img class="cart_img" src="{% static goods.img %}">
                <div class="cart_div1 fl"><p class="cart_p1">{{ goods.goodsname }}</p>
                    <p class="cart_p2">货号:20119845</p>
                    <p class="cart_p2">颜色/尺码:</p></div>


                <div class="cart_div2 fl"><span class="cart_span1"><span class="pa1">￥</span>
                    <a id="price"
                        class="pa2">{{ goods.prse }}</a>

                </span></div>



                <div class="cart_div3 fl">
                    <span id="jian" class="cart_span2">-</span>

                    <span id="shu" class="cart_span3">1</span>

                    <span id="jia"
                        class="cart_span4">+</span>

                </div>
                <div class="cart_div4 fl"><span class="cart_span5"><span class="pa1">￥</span><a
                        class="pa2">{{ goods.prse }}</a></span></div>
                <div class="cart_div5 fl"><span class="cart_span6">加入收藏夹</span><span class="cart_span7">删除</span></div>
            </div>


            <div class="main"></div>
            <div class="main"></div>
            <div class="main"></div>
            <div class="main"></div>
            <div class="main"></div>
            <div class="main"></div>
            <div class="main"></div>
            <div class="main"></div>
            <div class="c_footer">
                <div class="cf_left fl">
                    <p>
                        <input id="checkall" checked="checked" type="checkbox">全选
                        <a id="delete">删除选中的商品</a>
                        <a id="clear">清空购物车</a>

                    </p>
                </div>
                <div class="cf_middle fl">
                    <p>商品金额：<span class="money">0</span>元</p>
                    <p>运费：0元</p>
                    <p>可返积分：0</p>
                    <p class="_pall">总计：<span class="_all">0</span>元</p>
                </div>
                <div class="cf_right fl">
                    <div id="calculate">去结算</div>
                </div>
            </div>
        </div>
    </div>
    <!--foot部分-->
    <div id="footer">
        <div class="f_top">
            <div class="zheng fl">
                <img src="{% static 'img/footer/top1.jpg' %}">
                <h3>正品保证</h3>
                <h5>正品行货 开具发票</h5>
            </div>
            <div class="zheng fl">
                <img src="{% static 'img/footer/top2.jpg' %}">
                <h3>快捷配送</h3>
                <h5>严格包装 无损签收</h5>
            </div>
            <div class="zheng fl">
                <img src="{% static 'img/footer/top3.jpg' %}">
                <h3>便捷支付</h3>
                <h5>在线支付 货到付款</h5>
            </div>
        </div>
        <div class="f_middle">
            <img src="{% static 'img/footer/middle1.jpg' %}">
            <div class="list">
                <div class="lists fl">
                    <b>购物指南</b>
                    <a href="#">新用户注册/激活</a>
                    <a href="#">如何订购</a>
                    <a href="#">常见问题</a>
                </div>
                <div class="lists fl">
                    <b>会员中心</b>
                    <a href="#">会员权益</a>
                    <a href="#">美丽积分</a>
                    <a href="#">订单查询</a>
                    <a href="#">找回密码</a>
                </div>
                <div class="lists fl">
                    <b>配送服务</b>
                    <a href="#">物流跟踪</a>
                    <a href="#">免运费政策</a>
                </div>
                <div class="lists fl">
                    <b>支付说明</b>

                    <a href="#">货到付款</a>
                    <a href="#">在线支付</a>
                </div>
                <div class="lists fl">
                    <b>售后服务</b>
                    <a href="#">退换货政策</a>
                    <a href="#">退换货流程</a>
                    <a href="#">安全与保密</a>
                </div>
            </div>
            <div class="web">
                <img src="{% static 'img/footer/middle2.jpg' %}" class="fl">
                <div class="online fl">
                    <b>400-630-0077</b>
                    <h5>网站专线</h5>
                </div>
            </div>
        </div>
        <div class="f_bottom">
            <p>
                <a href="#">商城首页</a>
                <a href="#">官网首页</a>
                <a href="#">供应商登录</a>
                <a href="#">供货联系</a>
                <a href="#">收藏我们</a>
                <a href="#">公司简介</a>
                <a href="#">媒体报道</a>
                <a href="#">嘉丽购招聘</a>
                <a href="#">官方微博</a>
                <a href="#" style="border: none;">合作网站：范游网</a>
            </p><br>
            <p class="copyright">
                嘉丽购物有限责任公司 Copyright 2010-2014 jialigou All Rights Reserved
            </p>
            <p style="margin-top: 5px;">国家广电总局批号：广局[2010] 278号湘ICP备10203162号-3</p>
            <img src="{% static 'img/footer/bt5.gif' %}">
            <div class="security">
                <img src="{% static 'img/footer/bt1.jpg' %}" class="fl">
                <img src="{% static 'img/footer/bt2.jpg' %}" class="fl">
                <img src="{% static 'img/footer/bt3.gif' %}" class="fl">
                <img src="{% static 'img/footer/bt4.gif' %}" class="fl">
            </div>
        </div>
    </div>
</div>
<script>
    $("#jia").click(function() {
		var _num = $(this).prev("span").html();
		_num++;
		$(this).prev("span").html(_num);
		sum();
	});
	$(".cart_span2").click(function() {
		var _num = $(this).next("span").html();
		if(_num <= 1) {
			return
		}
		_num--;
		$(this).next("span").html(_num);
		sum();
	});
	//计算金额的函数
	function sum(){
				var c_index=$(".cart_span1").length;
				var arr = [];
				for(var i=0;i<$(".cart_span1").length;i++){
					var pri = $(".cart_span1").eq(i).text();
					var pri1 = pri.substring(1);
					var pri = parseInt(pri1);
					var _shuliang=$(".cart_span3").eq(i).html();
					var money = _shuliang * pri;
					arr.push(money);
				}
				var summoney = 0;
				for(var i = 0; i < arr.length; i++) {
					summoney += arr[i];
				}
				$(".money").html(summoney);
				$("._all").html(summoney);
			}
            $(".cart_span7").click(function() {
					alert("确定要删除所选商品吗");
					var good=$(this).parents(".main").find(".cart_p1").html();
					console.log(good);
					$(this).parents(".main").remove();
					sum();
					var index3=goodlist.length
					for(var i=0;i<index3;i++){
						if(good==goodlist[i].name){

							console.log(goodlist.splice(i,1));
							console.log(goodlist)
							$.cookie("cart","",{expires:0,path:"/"});
							$.cookie("cart",JSON.stringify(goodlist),{expires:30,path:"/"});
						}
					}


			});
	$("#checkall").click(function() {
			$("._true").prop("checked", this.checked)
		})
		//复选框的状态
	$("._true").click(function() {
			var $checked = $("._true").filter(':checked');
			$("#checkall").prop('checked', $checked.length == $("._true").length);
		})
    $(".cart_span6").click(function() {
			alert("请先登录");
			location.href = "load.html";
	})
		//清空购物车
	$("#clear").click(function() {
		alert("确定清空购物车吗");
		$.cookie("cart", "", {
			expires: 0,
			path: "/"
		});
		location.reload();
	});
	//结算
	$("#calculate").click(function() {
		alert("请先登录");
		location.href = "load.html";
	})

</script>
</body>
</html>

jlg01_01/templates/list.html
{% load static %}
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title>服装-连衣裙-嘉丽购</title>
		<link rel="stylesheet" type="text/css" href='{% static "css/list.css"  %}'/>
		<link rel="stylesheet" type="text/css" href='{% static "css/footer.css" %}' />
		<script src='{% static "js/jquery-1.12.0.js" %}' type="text/javascript" charset="utf-8"></script>
		<script src='{% static "js/jquery.cookie.js" %}' type="text/javascript" charset="utf-8"></script>
		<script type="text/javascript" src='{% static "js/json.js" %}' ></script>
		<script src='{% static "js/list.js" %}' type="text/javascript" charset="utf-8"></script>
		<script src='{% static "js/public.js" %}' type="text/javascript" charset="utf-8"></script>

	</head>

<body>

		<div class="bigbox">
			<!--header部分-->
			<div id="header">
				<div class="phone fl">
					<img src="{% static 'img/header/phone1.jpg' %}">
					<h6>电话热线</h6>
					<h5>400-630-0077</h5>
				</div>
				<div class="login fl">
					<a href="#" class="loads">[登录]</a>
					<a href="#" class="register">[免费注册]</a>
				</div>
				<div class="car fr">
					<p>
						<a href="#">我的嘉</a>
						<a href="#">我的订单</a>
						<a href="#">客户服务</a>
						<a href="#">电视会员激活</a>
						<a href="#">手机嘉丽购</a>
					</p>
				</div>
			</div>
			<!--nav部分-->
			<div id="nav">
				<div class="logo fl">
					<img src="{% static 'img/nav/nav1.jpg' %}">
				</div>
				<div class="search fl">
					<input class="text1" placeholder="请输入商品名称或电视商品编号" type="text">
					<input value="搜索" class="btn1" style="border: none;" type="button">
				</div>
				<div class="shopping fl">
					<span class="mycar">我的购物车</span>
					<div class="number">2</div>
				</div>
				<div class="TV">
					<p>
						<a href="index.html">首页</a>
						<a>TV直播</a>
						<a>嘉丽全球购</a>
						<a>水果生鲜</a>
					</p>
				</div>
				<div class="buy">
					<h6>订购热线</h6>
					<h5>400-630-0077</h5>
				</div>
				<div class="all">
					<p>全部商品分类</p>
				</div>
			</div>
			<!--content部分-->
			<div id="content">
				<div class="side">
					<div class="special"><a>特色推荐</a></div>
					<div class="con_product0 "></div>
					<div class="con_product0 "></div>
					<div class="con_product0 "></div>
					<div class="con_product0 "></div>


				</div>
				<div class="main">
					<div class="kind">
						<p>分类：
							<a href="#">全部</a>
							<a href="#">衬衫</a>
							<a href="#">T恤</a>
							<a href="#">针织</a>
							<a href="#">外套</a>
							<a href="#">羽绒服</a>
							<a href="#" class="active">裙子</a>
							<a href="#">女裤</a>
						</p>
						<p>品牌：
							<a href="#" class="active">全部</a>
							<a href="#">衬衫</a>
							<a href="#">迪非怡</a>
							<a href="#">水心花</a>
							<a href="#">诗尔莉</a>
							<a href="#">YKE</a>
							<a href="#">浪莎</a>
							<a href="#">桑普斯</a>
						</p>
					</div>
					<div class="sort">
						<h2 class="fl">排序</h2>
						<div class="sale fl">
							<a href="#">按销量排序</a>
						</div>
						<div class="time fl">
							<a href="#">按上架时间</a>
						</div>
						<div class="price fl">
							<a href="#">按价格</a>
						</div>
					</div>
					<div class="product">
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>
						<div class="fl _product">
							<div class="addCart">加入购物车</div>
							<div class="collect">收藏</div>
						</div>

					</div>
				</div>
			</div>

			<!--foot部分-->
			<div id="footer">
				<div class="f_top">
					<div class="zheng fl">
						<img src="{% static 'img/footer/top1.jpg' %}">
						<h3>正品保证</h3>
						<h5>正品行货 开具发票</h5>
					</div>
					<div class="zheng fl">
						<img src="{% static 'img/footer/top2.jpg' %}">
						<h3>快捷配送</h3>
						<h5>严格包装 无损签收</h5>
					</div>
					<div class="zheng fl">
						<img src="{% static 'img/footer/top3.jpg' %}">
						<h3>便捷支付</h3>
						<h5>在线支付 货到付款</h5>
					</div>
				</div>
				<div class="f_middle">
					<img src="{% static 'img/footer/middle1.jpg' %}">
					<div class="list">
						<div class="lists fl">
							<b>购物指南</b>
							<a href="#">新用户注册/激活</a>
							<a href="#">如何订购</a>
							<a href="#">常见问题</a>
						</div>
						<div class="lists fl">
							<b>会员中心</b>
							<a href="#">会员权益</a>
							<a href="#">美丽积分</a>
							<a href="#">订单查询</a>
							<a href="#">找回密码</a>
						</div>
						<div class="lists fl">
							<b>配送服务</b>
							<a href="#">物流跟踪</a>
							<a href="#">免运费政策</a>
						</div>
						<div class="lists fl">
							<b>支付说明</b>

							<a href="#">货到付款</a>
							<a href="#">在线支付</a>
						</div>
						<div class="lists fl">
							<b>售后服务</b>
							<a href="#">退换货政策</a>
							<a href="#">退换货流程</a>
							<a href="#">安全与保密</a>
						</div>
					</div>
					<div class="web">
						<img src="{% static 'img/footer/middle2.jpg' %}" class="fl">
						<div class="online fl">
							<b>400-630-0077</b>
							<h5>网站专线</h5>
						</div>
					</div>
				</div>
				<div class="f_bottom">
					<p>
						<a href="#">商城首页</a>
						<a href="#">官网首页</a>
						<a href="#">供应商登录</a>
						<a href="#">供货联系</a>
						<a href="#">收藏我们</a>
						<a href="#">公司简介</a>
						<a href="#">媒体报道</a>
						<a href="#">嘉丽购招聘</a>
						<a href="#">官方微博</a>
						<a href="#" style="border: none;">合作网站：范游网</a>
					</p><br>
					<p class="copyright">
						嘉丽购物有限责任公司 Copyright 2010-2014 jialigou All Rights Reserved
					</p>
					<p style="margin-top: 5px;">国家广电总局批号：广局[2010] 278号湘ICP备10203162号-3</p>
					<img src="{% static 'img/footer/bt5.gif' %}">
					<div class="security">
						<img src="{% static 'img/footer/bt1.jpg' %}" class="fl">
						<img src="{% static 'img/footer/bt2.jpg' %}" class="fl">
						<img src="{% static 'img/footer/bt3.gif' %}" class="fl">
						<img src="{% static 'img/footer/bt4.gif' %}" class="fl">
					</div>
				</div>
			</div>
		</div>
</body>

</html>

jlg01_01/templates/product.html
{% load static %}
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title>{{ goods.goodsname }}</title>
		<link rel="stylesheet" type="text/css" href='{% static "css/product.css" %}' />
		<link rel="stylesheet" type="text/css" href='{% static "css/footer.css" %}' />
		<script src='{% static "js/jquery-1.12.0.js" %}' type="text/javascript" charset="utf-8"></script>
		<script src='{% static "js/jquery.cookie.js" %}' type="text/javascript" charset="utf-8"></script>
		<script src='{% static "js/product.js" %}' type="text/javascript" charset="utf-8"></script>
		<script src='{% static "js/public.js" %}' type="text/javascript" charset="utf-8"></script>

	</head>

	<body>
    	<div class="bigbox">
			<!--header部分-->
			<div id="header">
				<div class="phone fl">
					<img src="{% static 'img/header/phone1.jpg' %}">
					<h6>电话热线</h6>
					<h5>400-630-0077</h5>
				</div>
				<div class="login fl">
					<a href="#" class="loads">[登录]</a>
					<a href="#" class="register">[免费注册]</a>
				</div>
				<div class="car fr">
					<p>
						<a href="#">我的嘉</a>
						<a href="#">我的订单</a>
						<a href="#">客户服务</a>
						<a href="#">电视会员激活</a>
						<a href="#">手机嘉丽购</a>
					</p>
				</div>
			</div>
			<!--nav部分-->
			<div id="nav">
				<div class="logo fl">
					<img src="{% static 'img/nav/nav1.jpg' %}">
				</div>
				<div class="search fl">
					<input class="text1" placeholder="请输入商品名称或电视商品编号" type="text">
					<input value="搜索" class="btn1" style="border: none;" type="button">
				</div>
				<div class="shopping fl">
                    <a href="/cart/">
					<span class="mycar">我的购物车</span>
					<div class="number">0</div></a>
				</div>
				<div class="TV">
					<p>
						<a href="index.html">首页</a>
						<a>TV直播</a>
						<a>嘉丽全球购</a>
						<a>水果生鲜</a>
					</p>
				</div>
				<div class="buy">
					<h6>订购热线</h6>
					<h5>400-630-0077</h5>
				</div>
				<div class="all">
					<p>全部商品分类</p>
				</div>
			</div>
			<!--content部分-->
			<div id="content">
				<div class="bag ">
					<p class="fl b">
						<b class="fl"><a href="#">服装、箱包</a></b>&gt;
					</p>
					<p class="fl _b">
						<a href="#">服饰</a>&gt;
						<a href="#">皮带</a>&gt;
						<a href="#">花花公子皮具男士必备三件套</a>
					</p>
				</div>
				<div id="pidai">
					<ul>
						<li class="active"><img src="{% static goods.img %}"></li>
						<li><img src="{% static goods.img %}"></li>
						<li><img src="{% static goods.img %}"></li>
					</ul>
					<div class="smallArea"></div>

				</div>
				<div id="buying">
					<p class="_p1">
						<a>{{ goods.goodsname }}</a>
						<b>(供货号：20119845)</b>
					</p>
					<div class="buy">
						<p class="p2">嘉丽价<span class="json_span1"><span class="pa1">￥</span><a class="pa2">{{ goods.prse }}</a></span></p>
						<p class="p2">积分<span>订购此商品可返回<a class="pa3">119*2</a>积分</span></p>
					</div>
					<div class="num">
						<p>
							</p><div class="shu fl">数量</div>
							<div class="yuan fl yuan1">-</div>
							<input value="1" class="fang fl" type="text">
							<!--<div class="fang fl">1</div>-->
							<div class="yuan fl yuan2">+</div>
						<p></p>
					</div>
					<div class="buying fl">立即购买</div>
                    <a href="{% url 'jlg:cart' goods.id %}"><div class="addCart fl">加入购物车</div></a>
					<div class="collect fl">收藏</div>
					<div class="bigArea">
						<ul>
							<li class="disp"><img src="{% static goods.img %}" class="bigimg"></li>
							<li><img src="{% static goods.img %}" class="bigimg"></li>
							<li><img src="{% static goods.img %}"class="bigimg"></li>
						</ul>
					</div>
				</div>
				<div id="small">
					<div class="pidai fl "><img src="{% static goods.img %}"></div>
					<div class="pidai fl"><img src="{% static goods.img %}"></div>
					<div class="pidai fl "><img src="{% static goods.img %}"></div>
				</div>
			</div>

			<!--foot部分-->
			<div id="footer">
				<div class="f_top">
					<div class="zheng fl">
						<img src="{% static 'img/footer/top1.jpg' %}">
						<h3>正品保证</h3>
						<h5>正品行货 开具发票</h5>
					</div>
					<div class="zheng fl">
						<img src="{% static 'img/footer/top2.jpg' %}">
						<h3>快捷配送</h3>
						<h5>严格包装 无损签收</h5>
					</div>
					<div class="zheng fl">
						<img src="{% static 'img/footer/top3.jpg' %}">
						<h3>便捷支付</h3>
						<h5>在线支付 货到付款</h5>
					</div>
				</div>
				<div class="f_middle">
					<img src="{% static 'img/footer/middle1.jpg' %}">
					<div class="list">
						<div class="lists fl">
							<b>购物指南</b>
							<a href="#">新用户注册/激活</a>
							<a href="#">如何订购</a>
							<a href="#">常见问题</a>
						</div>
						<div class="lists fl">
							<b>会员中心</b>
							<a href="#">会员权益</a>
							<a href="#">美丽积分</a>
							<a href="#">订单查询</a>
							<a href="#">找回密码</a>
						</div>
						<div class="lists fl">
							<b>配送服务</b>
							<a href="#">物流跟踪</a>
							<a href="#">免运费政策</a>
						</div>
						<div class="lists fl">
							<b>支付说明</b>

							<a href="#">货到付款</a>
							<a href="#">在线支付</a>
						</div>
						<div class="lists fl">
							<b>售后服务</b>
							<a href="#">退换货政策</a>
							<a href="#">退换货流程</a>
							<a href="#">安全与保密</a>
						</div>
					</div>
					<div class="web">
						<img src="{% static 'img/footer/middle2.jpg' %}" class="fl">
						<div class="online fl">
							<b>400-630-0077</b>
							<h5>网站专线</h5>
						</div>
					</div>
				</div>
				<div class="f_bottom">
					<p>
						<a href="#">商城首页</a>
						<a href="#">官网首页</a>
						<a href="#">供应商登录</a>
						<a href="#">供货联系</a>
						<a href="#">收藏我们</a>
						<a href="#">公司简介</a>
						<a href="#">媒体报道</a>
						<a href="#">嘉丽购招聘</a>
						<a href="#">官方微博</a>
						<a href="#" style="border: none;">合作网站：范游网</a>
					</p><br>
					<p class="copyright">
						嘉丽购物有限责任公司 Copyright 2010-2014 jialigou All Rights Reserved
					</p>
					<p style="margin-top: 5px;">国家广电总局批号：广局[2010] 278号湘ICP备10203162号-3</p>
					<img src="{% static 'img/footer/bt5.gif' %}">
					<div class="security">
						<img src="{% static 'img/footer/bt1.jpg' %}" class="fl">
						<img src="{% static 'img/footer/bt2.jpg' %}" class="fl">
						<img src="{% static 'img/footer/bt3.gif' %}" class="fl">
						<img src="{% static 'img/footer/bt4.gif' %}" class="fl">
					</div>
				</div>
			</div>
		</div>

    </body>

</html>